### ISSUE TITLE
Question about soma_tree (influence in tree.D(1))

### ISSUE THREAD

**Issue by natsrm** [cuntzlab/treestoolbox#1]
Hi,

First of all thank you for a great toolbox!!!

I have trees which were reconstructed with a "square" to represent the size of the soma. I wanted to delete this square, but still have a soma in my tree. For this I first used the function quaddiameter_tree, which removed the square, and then implemented the soma_tree function to create the soma; I used for maxD the value at tree.D(1), since this is the diammeter of the soma. After doing so, if I compare my original tree with the final one, soma_tree.D(1) is half the value of tree.D(1). Shouldn't they be the same value? Am I doing something incorrectly or could this be a small bug?

My code is something as:

`start_trees`
`tree = load_tree('females.mtr');`
`q_tree = quaddiameter_tree(tree, 0.01, [], []);`
`s_tree = soma_tree(q_tree, tree.D(1), [], []);`

And output is:

`tree.D(1)`
`ans = 18.8000`

`s_tree.D(1)`
`ans = 9.4000`

I appreciate any input you could give me!
Nat.

(The edit was not to overwrite the function with a variable)

**Comment by MarcelBeining** [comment]
Hi @natsrm ,
thank you for appreciation!
Generally my advice would be not overwriting functions with a variable (what you did in the case of `soma_tree`), otherwise the function cannot be called anymore in that script.
Concerning your issue, one possibility I can think of is that you used the `'-b'` options of `soma_tree` and have a multifurcation at your root node. In that case the diameter is decreased at each branch point to account for overlapping surfaces. --> If you have a trifurcation at your root: `18.8 / sqrt(2) / sqrt(2) = 9.4`

**Comment by natsrm** [comment]
Hi @MarcelBeining ,
Thank you for your fast reply!
For me the only option that appears as "available" to use with `soma_tree` is `'-s'`, and I use the default which is none. But yes you're right, I have multifurcations!!! So how can I fix this? Is there a way to not use option `'-b'` in `soma_tree`? Or is the best thing to just apply `elimt_tree`?
Thanks,
Nats

**Comment by natsrm** [comment]
@MarcelBeining An update:
I used `elimt_tree` to remove all multifurcations, and later applied `soma_tree` just as before. My outputs are still the same, even without having trifurcations...

**Comment by MarcelBeining** [comment]
Hi @natsrm ,
hm it's hard to say what the problem is without debugging it with your tree. Can you provide the tree as a download link so I can have a look? If you don't want to have it public, you can also send it to me via beining@fias.uni-frankfurt.de

**Comment by natsrm** [comment]
Hi @MarcelBeining ,
It's actually from Neuromorpho so no problem! The difference between this tree and the original from the repository, is I have aligned all of them with Vaa3D (Blastneuron). As a sample I am just sending you one:
https://wetransfer.com/downloads/0e0685c9901f23cf9f1e505e9207a8f220190402133039/b25b3ab59b2db9edd34255c661cae69120190402133039/565588

**Comment by MarcelBeining** [comment]
Hm, when I am using your providing tree and execute your code:

```
tree = load_tree('traced-WT-Female-hippo-122-1.CNG.swc_preprocessed.swc');

q_tree = quaddiameter_tree(tree, 0.01, [], []);
s_tree = soma_tree(q_tree, tree.D(1), [], []);

tree.D(1)
s_tree.D(1)
```

I get
```
ans =

   18.8000


ans =

   18.8000

```

Can you confirm, using the same code and file?
By the way, what version of TREES do you use? How did you download and install?

**Comment by natsrm** [comment]
Hi @MarcelBeining ,

Using the same file and the same code I still get the problem...

`tree.D(1)`
`ans = 18.8000`
`s_tree.D(1)`
`ans = 9.4000`

My version is 1.15, and I downloaded the zipped version from the website.

**Comment by MarcelBeining** [comment]
Oh no, 1.15 is a legacy version!
Please download from the newest master branch:
https://github.com/cuntzlab/treestoolbox/archive/master.zip
Overwrite your version and try again!
Sorry for the confusion!

I will tell @hermanncuntz to better mark on his webpage what the newest version is!

**Comment by natsrm** [comment]
Oh no! That's very unfortunate... Yes, then the webpage could use some changes! Ahaha because it talks about 1.15 as the "stable version", and even on the "how to get started", it specificly says to download v1.15, which is why I used that...

With the newest master branch it works fine!!! The values are the same!
Now this explains why I didn't understand when you talked about option `'-b'` in `soma_tree`, because in fact in v1.15 this option does not exist!

Thank you for all your help @MarcelBeining 👍 

**How to solve: Make sure you are not using v1.15, but the newest master branch! :)**
