### ISSUE TITLE
Segmenting Neurolucida imported tree

### ISSUE THREAD

**Issue by LauraDovek** [cuntzlab/treestoolbox#3]
Is there a way to break up an imported neuron (from neurolucida) into proximal, middle and distal branches? 
I was trying to use the path length function on the gui but am unsure what the correct procedure is.

**Comment by hermanncuntz** [comment]
This is not an issue with the software so please continue the discussion by contacting us directly.

One way to do this is for example, separating the tree in path length larger and smaller than 100 um:

tree = sample_tree;
Pvec = Pvec_tree (tree);
plot_tree (tree, Pvec > 100)
